name: setup_conan_for_mac
description: Add newest mac compilers to conan settings

inputs:
  os:
    required: true

runs:
  using: "composite"
  steps:
    - name: Modify conan settings
      if: inputs.os == 'macos-latest'
      run: |
        python3 -m pip install "conan<2"
        conan profile new default --detect --force
        conan config init --force
        if ! grep -q '"17.0"' ~/.conan/settings.yml; then
          sed -i '' '/"16.0"\]/s/\]/\, "17", "17.0"\]/' ~/.conan/settings.yml
          echo "Added Apple Clang 17.0 support to Conan settings"
        else
          echo "Apple Clang 17.0 already in Conan settings"
        fi
      shell: bash
