name: setup_conan_for_mac
description: Setup Conan macOS

inputs:
  os:
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Conan
      if: inputs.os == 'macos-latest'
      run: |
        python3 -m pip install conan
        conan profile detect --force
      shell: bash
