import os
import os.path
import sys
sys.path += ["../../build"]
import global_config
from   global_config import LIBUTIL
from   global_config import add_static_library
from   global_config import add_header
from   global_config import get_targets
from   global_config import add_program

bin_path = "../bin"
package  = "util"
env  = Environment()
conf = global_config.get_conf(os.getcwd() , package , 2)
conf.update_env( env , [ LIBUTIL ] , ext_liblist = ["pthread" , "m" , "lapack" , "z"] , link = True)

add_program(env , conf , bin_path , "replace.x"         , "replace.c"  )
add_program(env , conf , bin_path , "matrix_test"         , "matrix_test.c"  )
add_program(env , conf , bin_path , "ens_tar.x"         , "ens_tar.c"  )
add_program(env , conf , bin_path , "file_open.x"       , "file_open.c" )
add_program(env , conf , bin_path , "grane_fix"         , "grane_fix.c" )
add_program(env , conf , bin_path , "grdecl_to_ascii.x" , "grdecl_to_ascii.c" )
add_program(env , conf , bin_path , "parser_test.x"     , "parser_test.c" )
add_program(env , conf , bin_path , "mem_free.x"        , "mem_free.c" )
add_program(env , conf , bin_path , "eol-fix.x"         , "eol-fix.c" )
add_program(env , conf , bin_path , "util-test"         , "util-test.c" )

(local , SDP_INSTALL) = get_targets( env , conf )
Default( local )



