# -*-python-*-
#
 
import os
import os.path

# 
# Set umask and file rights so that things are built and installed readable by others
#

umask = os.umask(002)


#
# Create variables instdir, bindir, libdir, and incdir, and alias install:
#

basedir = os.environ['SDP_BINDIST_ROOT'] # directory for "binary" distribution
instdir = os.environ['SDP_BINDIST']      # install directory 
 
bindir = instdir + '/bin'
libdir = instdir + '/lib'
incdir = instdir + '/inc'

Alias('install',[bindir])

# -----------------------------------------------

#viewer = '-D\'VIEWER=\"' + bindir + '/qiv\"\'' 

opt = Environment(CXXFLAGS = '-O3' ,
                  CFLAGS   = '-O2 -std=gnu99 -g -Wall -fPIC' ,
#                  LINKFLAGS  = '-static' ,
#                  CPPFLAGS = viewer ,
                  CPPPATH = ['.','..',incdir] ,
#                  CPPPATH = ['.',incdir] ,
                  LIBPATH = ['.', '..' ,libdir])
#                  LIBPATH = ['.',libdir])

lib_list = ['ecl','plot','util','plplotd','m','z','pthread']

object_files =  opt.Object('testplot.cc')
object_files += opt.Object('plot_const_cxx.cxx')

bin_files = opt.Program('testplot', object_files , LIBS=lib_list)

header_files = [ 'plot.hxx' , 'plot_range.hxx' ]

#Install(bindir,bin_files)
