from enum import IntEnum


class SummaryVarType(IntEnum):
    RD_SMSPEC_INVALID_VAR = 0
    RD_SMSPEC_FIELD_VAR = 1
    RD_SMSPEC_REGION_VAR = 2
    RD_SMSPEC_GROUP_VAR = 3
    RD_SMSPEC_WELL_VAR = 4
    RD_SMSPEC_SEGMENT_VAR = 5
    RD_SMSPEC_BLOCK_VAR = 6
    RD_SMSPEC_AQUIFER_VAR = 7
    RD_SMSPEC_COMPLETION_VAR = 8
    RD_SMSPEC_NETWORK_VAR = 9
    RD_SMSPEC_REGION_2_REGION_VAR = 10
    RD_SMSPEC_LOCAL_BLOCK_VAR = 11
    RD_SMSPEC_LOCAL_COMPLETION_VAR = 12
    RD_SMSPEC_LOCAL_WELL_VAR = 13
    RD_SMSPEC_MISC_VAR = 14
