import typing

from .rd_sum_var_type import SummaryVarType

__all__ = ["ResdataSMSPECNode"]

class ResdataSMSPECNode:
    def __eq__(self, arg0: object) -> bool: ...
    def __gt__(self, arg0: ResdataSMSPECNode) -> bool: ...
    def __hash__(self) -> int: ...
    def __init__(self) -> None: ...
    def __lt__(self, arg0: ResdataSMSPECNode) -> bool: ...
    def get_key1(self) -> str | None: ...
    def get_key2(self) -> str | None: ...
    def get_num(self) -> int | None: ...
    def is_historical(self) -> bool: ...
    def is_rate(self) -> bool: ...
    def is_total(self) -> bool: ...
    def var_type(self) -> SummaryVarType: ...
    @property
    def default(self) -> float: ...
    @property
    def keyword(self) -> str: ...
    @property
    def num(self) -> int | None: ...
    @property
    def unit(self) -> str: ...
    @property
    def wgname(self) -> str | None: ...
