import typing

__all__: list[str] = ["CPolyline"]

class CPolyline:
    def __init__(
        self,
        name: str | None = None,
        init_points: typing.Iterable[tuple[float, float]] = (),
    ) -> None: ...
    @staticmethod
    def createFromXYZFile(filename: str, name: str | None = None) -> CPolyline: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> tuple[float, float]: ...
    def __eq__(self, other: object) -> bool: ...
    def __add__(self, other: typing.Iterable[tuple[float, float]]) -> CPolyline: ...
    def __radd__(self, other: typing.Iterable[tuple[float, float]]) -> CPolyline: ...
    def __iadd__(self, other: typing.Iterable[tuple[float, float]]) -> typing.Self: ...
    def addPoint(self, xc: float, yc: float, front: bool = False) -> None: ...
    def getName(self) -> str | None: ...
    def segmentIntersects(
        self, p1: tuple[float, float], p2: tuple[float, float]
    ) -> bool: ...
    def intersects(self, polyline: typing.Iterable[tuple[float, float]]) -> bool: ...
    def segmentLength(self) -> float: ...
    def extendToBBox(
        self, bbox: typing.Sequence[tuple[float, float]], start: bool = True
    ) -> CPolyline: ...
    def connect(
        self, target: typing.Sequence[tuple[float, float]]
    ) -> list[tuple[float, float]]: ...
    def unzip(self) -> tuple[list[float], list[float]]: ...
    def unzip2(self) -> tuple[list[float], list[float]]: ...
