set_property( TEST ecl_fault_block_layer_statoil      PROPERTY LABELS StatoilData )
set_property( TEST ecl_fmt              PROPERTY LABELS StatoilData )
set_property( TEST ecl_coarse_test      PROPERTY LABELS StatoilData )
set_property( TEST ecl_restart_test     PROPERTY LABELS StatoilData )
set_property( TEST ecl_lgr_test1        PROPERTY LABELS StatoilData )
set_property( TEST ecl_lgr_test2        PROPERTY LABELS StatoilData )
set_property( TEST ecl_lgr_test3        PROPERTY LABELS StatoilData )
set_property( TEST ecl_grid_lgr_name    PROPERTY LABELS StatoilData )
set_property( TEST ecl_grid_simple      PROPERTY LABELS StatoilData )
set_property( TEST ecl_grid_export      PROPERTY LABELS StatoilData )
set_property( TEST ecl_dualp            PROPERTY LABELS StatoilData )
set_property( TEST ecl_sum_test         PROPERTY LABELS StatoilData )

set_property( TEST ecl_sum_report_step_equal1 PROPERTY LABELS StatoilData )
set_property( TEST ecl_sum_report_step_equal2 PROPERTY LABELS StatoilData )
set_property( TEST ecl_sum_report_step_equal3 PROPERTY LABELS StatoilData )
set_property( TEST ecl_sum_report_step_equal4 PROPERTY LABELS StatoilData )
set_property( TEST ecl_sum_report_step_equal5 PROPERTY LABELS StatoilData )
set_property( TEST ecl_sum_report_step_equal6 PROPERTY LABELS StatoilData )

set_property( TEST ecl_sum_report_step_compatible1 PROPERTY LABELS StatoilData )
set_property( TEST ecl_sum_report_step_compatible2 PROPERTY LABELS StatoilData )
set_property( TEST ecl_sum_report_step_compatible3 PROPERTY LABELS StatoilData )
set_property( TEST ecl_sum_report_step_compatible4 PROPERTY LABELS StatoilData )
set_property( TEST ecl_sum_report_step_compatible5 PROPERTY LABELS StatoilData )
set_property( TEST ecl_sum_report_step_compatible6 PROPERTY LABELS StatoilData )



set_property( TEST ecl_grid_dims1 PROPERTY LABELS StatoilData )
set_property( TEST ecl_grid_dims2 PROPERTY LABELS StatoilData )
set_property( TEST ecl_grid_dims3 PROPERTY LABELS StatoilData )
set_property( TEST ecl_grid_dims4 PROPERTY LABELS StatoilData )
set_property( TEST ecl_grid_dims5 PROPERTY LABELS StatoilData )
set_property( TEST ecl_nnc_test1 PROPERTY LABELS StatoilData )
set_property( TEST ecl_nnc_test2 PROPERTY LABELS StatoilData )
set_property( TEST ecl_nnc_test3 PROPERTY LABELS StatoilData )
set_property( TEST ecl_nnc_test4 PROPERTY LABELS StatoilData )
set_property( TEST ecl_nnc_test5 PROPERTY LABELS StatoilData )

set_property( TEST ecl_grid_fwrite PROPERTY LABELS StatoilData)
set_property( TEST ecl_file PROPERTY LABELS StatoilData)
set_property( TEST ecl_rsthead PROPERTY LABELS StatoilData)
set_property( TEST ecl_region PROPERTY LABELS StatoilData)
set_property( TEST ecl_region2region PROPERTY LABELS StatoilData)
set_property( TEST ecl_grid_case PROPERTY LABELS StatoilData)
set_property( TEST ecl_rft_rft PROPERTY LABELS StatoilData)
set_property( TEST ecl_rft_plt PROPERTY LABELS StatoilData)
set_property( TEST ecl_rft_rft_rw PROPERTY LABELS StatoilData)
set_property( TEST ecl_sum_case_exists PROPERTY LABELS StatoilData)
set_property( TEST ecl_grid_volume1 PROPERTY LABELS StatoilData)
set_property( TEST ecl_grid_volume2 PROPERTY LABELS StatoilData)
#set_property( TEST ecl_grid_volume3 PROPERTY LABELS StatoilData)
set_property( TEST ecl_grid_cell_contains2 PROPERTY LABELS StatoilData )
set_property( TEST ecl_grid_cell_contains3 PROPERTY LABELS StatoilData )
set_property( TEST ecl_grid_cell_contains4 PROPERTY LABELS StatoilData )
set_property( TEST ecl_grid_cell_volume2 PROPERTY LABELS StatoilData )
set_property( TEST ecl_grid_cell_volume3 PROPERTY LABELS StatoilData )
set_property( TEST ecl_nnc_export1 PROPERTY LABELS StatoilData )
set_property( TEST ecl_nnc_export2 PROPERTY LABELS StatoilData )
set_property( TEST ecl_nnc_export3 PROPERTY LABELS StatoilData )
set_property( TEST ecl_nnc_export4 PROPERTY LABELS StatoilData )
set_property( TEST ecl_nnc_export5 PROPERTY LABELS StatoilData )
set_property( TEST ecl_nnc_export6 PROPERTY LABELS StatoilData )
set_property( TEST ecl_nnc_export7 PROPERTY LABELS StatoilData )
set_property( TEST ecl_nnc_export_get_tran PROPERTY LABELS StatoilData )
set_property( TEST ecl_grid_cell_contains2 PROPERTY LABELS StatoilData )
set_property( TEST ecl_grid_copy_statoil1 PROPERTY LABELS StatoilData )
set_property( TEST ecl_grid_copy_statoil2 PROPERTY LABELS StatoilData )
set_property( TEST ecl_grid_copy_statoil3 PROPERTY LABELS StatoilData )
set_property( TEST ecl_grid_copy_statoil4 PROPERTY LABELS StatoilData )
set_property( TEST ecl_layer_statoil PROPERTY LABELS StatoilData )
set_property( TEST ecl_grid_layer_contains1 PROPERTY LABELS StatoilData )
set_property( TEST ecl_grid_layer_contains2 PROPERTY LABELS StatoilData )
set_property( TEST ecl_grid_ecl2015_2 PROPERTY LABELS StatoilData )
