/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window1 (void);
GtkWidget* create_filechooserdialog1 (void);
GtkWidget* create_dialog1 (void);
GtkWidget* create_window2 (void);
