python_include_path = "/usr/include/python2.6"
env = Environment( CPPPATH = [ python_include_path  ])
LIB = env.SharedLibrary('pycfile' , ["pycfile.c"])
env.Install("../slib" , LIB) 
Default( "../slib" )