import typing

__all__ = ["FileMode"]

class FileMode:
    CLOSE_STREAM: typing.ClassVar[FileMode]
    DEFAULT: typing.ClassVar[FileMode]
    WRITABLE: typing.ClassVar[FileMode]
    __members__: typing.ClassVar[dict[str, FileMode]]
    def __and__(self, arg0: FileMode) -> FileMode: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: typing.Any) -> bool: ...
    def __getstate__(self) -> int: ...
    def __gt__(self, other: typing.Any) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __init__(self, value: typing.SupportsInt) -> None: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> FileMode: ...
    def __le__(self, other: typing.Any) -> bool: ...
    def __lt__(self, other: typing.Any) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, arg0: FileMode) -> FileMode: ...
    def __setstate__(self, state: typing.SupportsInt) -> None: ...
    def __xor__(self, arg0: FileMode) -> FileMode: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
