import typing

__all__ = ["FileMode", "FileType"]

class FileMode:
    CLOSE_STREAM: typing.ClassVar[FileMode]
    DEFAULT: typing.ClassVar[FileMode]
    WRITABLE: typing.ClassVar[FileMode]
    __members__: typing.ClassVar[dict[str, FileMode]]
    def __and__(self, arg0: FileMode) -> FileMode: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: typing.Any) -> bool: ...
    def __getstate__(self) -> int: ...
    def __gt__(self, other: typing.Any) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __init__(self, value: typing.SupportsInt) -> None: ...
    def __int__(self) -> int: ...
    def __invert__(self) -> FileMode: ...
    def __le__(self, other: typing.Any) -> bool: ...
    def __lt__(self, other: typing.Any) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, arg0: FileMode) -> FileMode: ...
    def __setstate__(self, state: typing.SupportsInt) -> None: ...
    def __xor__(self, arg0: FileMode) -> FileMode: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class FileType:
    DATA: typing.ClassVar[FileType]
    EGRID: typing.ClassVar[FileType]
    GRID: typing.ClassVar[FileType]
    INIT: typing.ClassVar[FileType]
    OTHER: typing.ClassVar[FileType]
    RESTART: typing.ClassVar[FileType]
    RFT: typing.ClassVar[FileType]
    SUMMARY: typing.ClassVar[FileType]
    SUMMARY_HEADER: typing.ClassVar[FileType]
    UNIFIED_RESTART: typing.ClassVar[FileType]
    UNIFIED_SUMMARY: typing.ClassVar[FileType]
    __members__: typing.ClassVar[dict[str, FileType]]
    def __eq__(self, other: object) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __init__(self, value: typing.SupportsInt) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __setstate__(self, state: typing.SupportsInt) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

def _get_file_type(filename: str) -> tuple[FileType, bool, int]: ...
