__all__: list[str] = ["WellSegment"]

class WellSegment:
    def __init__(self) -> None: ...
    def branchId(self) -> int: ...
    def depth(self) -> float: ...
    def diameter(self) -> float: ...
    def id(self) -> int: ...
    def isActive(self) -> bool: ...
    def isMainStem(self) -> bool: ...
    def isNearestWellHead(self) -> bool: ...
    def length(self) -> float: ...
    def linkCount(self) -> int: ...
    def outletId(self) -> int: ...
    def totalLength(self) -> float: ...
