import typing

__all__ = ["WellConnectionDirection"]

class WellConnectionDirection:
    __members__: typing.ClassVar[dict[str, WellConnectionDirection]]
    well_conn_dirX: typing.ClassVar[WellConnectionDirection]
    well_conn_dirY: typing.ClassVar[WellConnectionDirection]
    well_conn_dirZ: typing.ClassVar[WellConnectionDirection]
    well_conn_fracX: typing.ClassVar[WellConnectionDirection]
    well_conn_fracY: typing.ClassVar[WellConnectionDirection]
    def __eq__(self, other: object) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __init__(self, value: typing.SupportsInt) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __setstate__(self, state: typing.SupportsInt) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
