from .well_connection_direction_enum import WellConnectionDirection

__all__: list[str] = ["WellConnection"]

class WellConnection:
    def __eq__(self, arg0: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __init__(self) -> None: ...
    def connectionFactor(self) -> float: ...
    def direction(self) -> WellConnectionDirection: ...
    def gasRate(self) -> float: ...
    def gasRateSI(self) -> float: ...
    def ijk(self) -> tuple[int, int, int]: ...
    def isFractureConnection(self) -> bool: ...
    def isMatrixConnection(self) -> bool: ...
    def isMultiSegmentWell(self) -> bool: ...
    def isOpen(self) -> bool: ...
    def oilRate(self) -> float: ...
    def oilRateSI(self) -> float: ...
    def segmentId(self) -> int: ...
    def volumeRate(self) -> float: ...
    def volumeRateSI(self) -> float: ...
    def waterRate(self) -> float: ...
    def waterRateSI(self) -> float: ...
