import typing

from .well_state import WellState

__all__ = ["WellTimeLine"]

class WellTimeLine:
    def __getitem__(self, index: typing.SupportsInt) -> WellState: ...
    def __init__(self) -> None: ...
    def __len__(self) -> int: ...
    def getName(self) -> str: ...
