import typing

from resdata.grid import Grid
from resdata.resfile import ResdataFile
from resdata.well import WellTimeLine

__all__ = ["WellInfo"]

class WellInfo:
    def __contains__(self, item: str) -> bool: ...
    def __getitem__(self, item: typing.SupportsInt | str) -> WellTimeLine: ...
    def __init__(
        self,
        grid: Grid,
        rst_file: None | list[str | ResdataFile] | str | ResdataFile = None,
        load_segment_information: bool = True,
    ) -> None: ...
    def __iter__(self) -> typing.Iterator[WellTimeLine]: ...
    def __len__(self) -> int: ...
    def addWellFile(
        self, rst_file: str | ResdataFile, load_segment_information: bool
    ) -> None: ...
    def allWellNames(self) -> list[str]: ...
    def hasWell(self, well_name: str) -> bool: ...
