import typing

from resdata.util.util import CTime

from .well_connection import WellConnection
from .well_segment import WellSegment
from .well_type_enum import WellType

__all__ = ["WellState"]

class WellState:
    def __getitem__(self, idx: typing.SupportsInt) -> WellSegment: ...
    def __init__(self) -> None: ...
    def __len__(self) -> int: ...
    def gasRate(self) -> float: ...
    def gasRateSI(self) -> float: ...
    def globalConnections(self) -> list[WellConnection]: ...
    def hasGlobalConnections(self) -> bool: ...
    def hasSegmentData(self) -> bool: ...
    def igetSegment(self, seg_idx: typing.SupportsInt) -> WellSegment: ...
    def isMultiSegmentWell(self) -> bool: ...
    def isOpen(self) -> bool: ...
    def name(self) -> str: ...
    def numSegments(self) -> int: ...
    def oilRate(self) -> float: ...
    def oilRateSI(self) -> float: ...
    def reportNumber(self) -> int: ...
    def segments(self) -> list[WellSegment]: ...
    def simulationTime(self) -> CTime: ...
    def volumeRate(self) -> float: ...
    def volumeRateSI(self) -> float: ...
    def waterRate(self) -> float: ...
    def waterRateSI(self) -> float: ...
    def wellHead(self) -> WellConnection | None: ...
    def wellNumber(self) -> int: ...
    def wellType(self) -> WellType: ...
