import typing

__all__ = ["WellType"]

class WellType:
    GAS_INJECTOR: typing.ClassVar[WellType]
    OIL_INJECTOR: typing.ClassVar[WellType]
    PRODUCER: typing.ClassVar[WellType]
    WATER_INJECTOR: typing.ClassVar[WellType]
    ZERO: typing.ClassVar[WellType]
    __members__: typing.ClassVar[dict[str, WellType]]
    def __eq__(self, other: object) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __init__(self, value: typing.SupportsInt) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __setstate__(self, state: typing.SupportsInt) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
