python_include_path = "/prog/sdpsoft/python2.4/include/python2.4"
env = Environment( CPPPATH = [ python_include_path  ])
LIB = env.SharedLibrary('cfile' , ["cfile.c"])
env.Install("../slib" , LIB) 
Default( "../slib" )