from typing import ClassVar, SupportsInt

__all__ = ["FortIO"]

class FortIO:
    APPEND_MODE: ClassVar[Mode]
    READ_AND_WRITE_MODE: ClassVar[Mode]
    READ_MODE: ClassVar[Mode]
    WRITE_MODE: ClassVar[Mode]
    @staticmethod
    def is_fortran_file(filename: str, endian_flip: bool = True) -> bool: ...
    def __init__(
        self,
        file_name: str,
        mode: Mode = ...,
        fmt_file: bool = False,
        endian_flip_header: bool = True,
    ) -> None: ...
    def close(self) -> None: ...
    def filename(self) -> str: ...
    def get_position(self) -> int: ...
    def seek(self, position: SupportsInt, whence: SupportsInt = 0) -> bool: ...
    def truncate(self, size: SupportsInt | None = None) -> None: ...

class Mode:
    APPEND_MODE: ClassVar[Mode]
    READ_AND_WRITE_MODE: ClassVar[Mode]
    READ_MODE: ClassVar[Mode]
    WRITE_MODE: ClassVar[Mode]
    __members__: ClassVar[dict[str, Mode]]
    def __eq__(self, other: object) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __init__(self, value: SupportsInt) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __setstate__(self, state: SupportsInt) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
