import datetime
from typing import SupportsFloat, SupportsInt, overload

from .rd_kw import ResdataKW

__all__ = ["ResdataFileView"]

class ResdataFileView:
    def __contains__(self, arg0: str) -> bool: ...
    @overload
    def __getitem__(self, index: str) -> list[ResdataKW]: ...
    @overload
    def __getitem__(self, index: SupportsInt) -> ResdataKW: ...
    @overload
    def __getitem__(self, index: slice) -> list[ResdataKW]: ...
    def __init__(self) -> None: ...
    def __len__(self) -> int: ...
    def block_view(self, kw: str, kw_index: SupportsInt) -> ResdataFileView: ...
    def block_view2(
        self, start_kw: str | None, stop_kw: str | None, start_index: SupportsInt
    ) -> ResdataFileView: ...
    def iget_named_kw(self, kw_name: str, index: SupportsInt) -> ResdataKW: ...
    def num_keywords(self, kw: str) -> int: ...
    def restart_view(
        self,
        seqnum_index: SupportsInt | None = None,
        report_step: SupportsInt | None = None,
        sim_time: datetime.date | datetime.datetime | None = None,
        sim_days: SupportsFloat | None = None,
    ) -> ResdataFileView: ...
    def unique_kw(self) -> list[str]: ...
    def unique_size(self) -> int: ...
