import datetime
import typing

from resdata.rd_util import FileMode, FileType

from .fortio import FortIO
from .rd_file_view import ResdataFileView
from .rd_kw import ResdataKW

__all__: list[str] = ["ResdataFile"]

class ResdataFile:
    @staticmethod
    def contains_report_step(
        filename: str, report_step: typing.SupportsInt
    ) -> bool: ...
    @staticmethod
    def contains_sim_time(
        filename: str, dtime: datetime.date | datetime.datetime
    ) -> bool: ...
    @staticmethod
    def file_report_list(filename: str) -> list[int]: ...
    @staticmethod
    def get_filetype(filename: str) -> tuple[FileType, int | None, bool | None]: ...
    def __contains__(self, kw: str) -> bool: ...
    def __getitem__(
        self, index: typing.SupportsInt | str
    ) -> ResdataKW | list[ResdataKW]: ...
    def __init__(
        self,
        filename: str,
        flags: FileMode = ...,
        index_filename: str | None = None,
    ) -> None: ...
    def __len__(self) -> int: ...
    def block_view(self, kw: str, kw_index: typing.SupportsInt) -> ResdataFileView: ...
    def block_view2(
        self, start_kw: str | None, stop_kw: str | None, start_index: typing.SupportsInt
    ) -> ResdataFileView: ...
    def close(self) -> None: ...
    def fwrite(self, fortio: FortIO) -> None: ...
    def get_filename(self) -> str: ...
    def has_kw(self, kw: str, num: typing.SupportsInt = 0) -> bool: ...
    def has_report_step(self, report_step: typing.SupportsInt) -> bool: ...
    def has_sim_time(self, dtime: datetime.date | datetime.datetime) -> bool: ...
    def iget_kw(self, index: typing.SupportsInt, copy: bool = False) -> ResdataKW: ...
    def iget_named_kw(
        self, kw_name: str, index: typing.SupportsInt, copy: bool = False
    ) -> ResdataKW: ...
    def iget_restart_sim_days(self, index: typing.SupportsInt) -> float: ...
    def iget_restart_sim_time(self, index: typing.SupportsInt) -> datetime.datetime: ...
    def keys(self) -> typing.KeysView[str]: ...
    def num_named_kw(self, kw: str) -> int: ...
    def num_report_steps(self) -> int: ...
    def restart_get_kw(
        self, kw_name: str, dtime: datetime.date | datetime.datetime, copy: bool = False
    ) -> ResdataKW: ...
    def restart_view(
        self,
        seqnum_index: typing.SupportsInt | None = None,
        report_step: typing.SupportsInt | None = None,
        sim_time: datetime.datetime | datetime.date | None = None,
        sim_days: typing.SupportsFloat | None = None,
    ) -> ResdataFileView: ...
    def save_kw(self, kw: ResdataKW) -> None: ...
    def write_index(self, index_file_name: str) -> None: ...
    @property
    def dates(self) -> list[datetime.datetime] | None: ...
    @property
    def global_view(self) -> ResdataFileView: ...
    @property
    def headers(self) -> list[tuple[str, int, str]]: ...
    @property
    def report_dates(self) -> list[datetime.datetime] | None: ...
    @property
    def report_list(self) -> list[int]: ...
    @property
    def report_steps(self) -> list[int]: ...
    @property
    def size(self) -> int: ...
    @property
    def unique_size(self) -> int: ...
