from typing import Iterable, SupportsFloat, SupportsInt

from resdata.geometry import CPolylineCollection, Polyline
from resdata.util.util import IntVector

from .fault_block_layer import FaultBlockLayer

__all__ = ["FaultBlock", "FaultBlockCell"]

class FaultBlock:
    def __getitem__(self, index: SupportsInt) -> FaultBlockCell: ...
    def __init__(self) -> None: ...
    def __len__(self) -> int: ...
    def add_cell(self, i: SupportsInt, j: SupportsInt) -> None: ...
    def assign_to_region(self, region_id: SupportsInt) -> None: ...
    def contains_polyline(self, polyline: Iterable[tuple[float, float]]) -> bool: ...
    def count_inside(self, polygon: Iterable[tuple[float, float]]) -> int: ...
    def get_block_id(self) -> int: ...
    def get_centroid(self) -> tuple[float, float]: ...
    def get_edge_polygon(self) -> Polyline: ...
    def get_global_index_list(self) -> IntVector: ...
    def get_neighbours(
        self, polylines: CPolylineCollection | None = None, connected_only: bool = True
    ) -> list[FaultBlock]: ...
    def get_parent_layer(self) -> FaultBlockLayer: ...
    def get_region_list(self) -> IntVector: ...

class FaultBlockCell:
    def __init__(
        self,
        i: SupportsInt,
        j: SupportsInt,
        k: SupportsInt,
        x: SupportsFloat,
        y: SupportsFloat,
        z: SupportsFloat,
    ) -> None: ...
    @property
    def i(self) -> int: ...
    @i.setter
    def i(self, arg0: SupportsInt) -> None: ...
    @property
    def j(self) -> int: ...
    @j.setter
    def j(self, arg0: SupportsInt) -> None: ...
    @property
    def k(self) -> int: ...
    @k.setter
    def k(self, arg0: SupportsInt) -> None: ...
    @property
    def x(self) -> float: ...
    @x.setter
    def x(self, arg0: SupportsFloat) -> None: ...
    @property
    def y(self) -> float: ...
    @y.setter
    def y(self, arg0: SupportsFloat) -> None: ...
    @property
    def z(self) -> float: ...
    @z.setter
    def z(self, arg0: SupportsFloat) -> None: ...
