import os
import os.path
import sys
sys.path += ["../../../build"]
import global_config
from   global_config import LIBUTIL


SDP_ROOT = ARGUMENTS.get('SDP_ROOT','/d/proj/bg/enkf')
conf = global_config.get_conf(SDP_ROOT , os.getcwd() , 3)
env  = Environment()

conf.update_env( env , [ LIBUTIL ] , ext_liblist = ["pthread" , "m" , "z"] , link = True)
            

##################################################################



def add_program(env , conf , target , src , SDP_INSTALL = False):
    P = env.Program( target , src )
    env.InstallProgram( "../../bin" , P)
    if conf.SDP_BIN:
        if SDP_INSTALL:
            env.InstallProgram(conf.SDP_BIN , P)


add_program(env , conf , "bfs_extract"       , "bfs_extract.c" , True)
add_program(env , conf , "bls.x"             , "bls.c"         , True)
add_program(env , conf , "brm.x"             , "brm.c"         , True)
add_program(env , conf , "brot.x"            , "brot.c"        , True)
add_program(env , conf , "bcp.x"             , "bcp.c"         , True)

install = env.Alias('install',"../../bin")
if SDP_ROOT:
    env.Alias('SDP_INSTALL' , conf.SDP_BIN)

Default( install )


         