import os
import os.path
import sys
sys.path += ["../../../build"]
import global_config
from   global_config import LIBUTIL
from   global_config import add_static_library
from   global_config import add_header
from   global_config import get_targets
from   global_config import add_program

bin_path = "../../bin"
package  = "util"
env      = Environment()
conf     = global_config.get_conf(os.getcwd() , package , 3)
conf.update_env( env , [ LIBUTIL ] , ext_liblist = ["pthread" , "m" , "z"] , link = True)

            
add_program(env , conf , bin_path , "bfs_extract"       , "bfs_extract.c")
add_program(env , conf , bin_path , "bls.x"             , "bls.c"        )
add_program(env , conf , bin_path , "brm.x"             , "brm.c"        )
add_program(env , conf , bin_path , "brot.x"            , "brot.c"       )
add_program(env , conf , bin_path , "bcp.x"             , "bcp.c"        )

(local ) = get_targets( env , conf )
Default( local )

         
