SConscript(["libsched/SConstruct",
            "librms/SConstruct",
            "libecl/SConstruct",
            "libjob_queue/SConstruct",
            "libplot/SConstruct",
            "libutil/SConstruct",
            "libconfig/SConstruct",
            "libenkf/SConstruct"])
            
           
        
