import os
import os.path
import sys
sys.path += ["../../build"]
import global_config
from   global_config import LIBUTIL
from   global_config import LIBECL



def needs_update( target_file , src_file):
    if not os.path.exists( target_file ):
       return True
       
    src_stat    = os.stat( src_file )
    target_stat = os.stat( target_file )

    if src_stat[8] > target_stat[8]:
        return True
    else:
        return False
    

SDP_ROOT = ARGUMENTS.get('SDP_ROOT','/d/proj/bg/enkf')
conf     = global_config.get_conf(SDP_ROOT , os.getcwd() , 2)
env      = Environment()
conf.update_env( env , [ LIBECL , LIBUTIL ] , link = False)


vector_list = ["int" , "float" , "double" , "bool" , "time_t" , "long"]

src_list = Split("mzran.c set.c hash_node.c hash_sll.c hash.c list_node.c list.c node_data.c node_ctype.c util.c thread_pool.c msg.c arg_pack.c path_fmt.c menu.c subst_list.c subst_func.c vector.c parser.c stringlist.c matrix.c matrix_lapack.c matrix_blas.c conf_new.c buffer.c block_fs.c log.c template.c timer.c")

header_list = Split("mzran.h set.h hash.h hash_node.h hash_sll.h list_node.h list.h node_data.h node_ctype.h util.h thread_pool.h msg.h arg_pack.h path_fmt.h  stringlist.h menu.h subst_list.h subst_func.h vector.h parser.h matrix.h matrix_lapack.h matrix_blas.h conf_new.h buffer.h block_fs.h log.h template.h timer.h")

for type in vector_list:
    header_file = "%s_vector.h" % type
    src_file    = "%s_vector.c" % type
    if needs_update( header_file , "vector_template.h"):
        os.system("sed -e \'s/<TYPE>/%s/g\' vector_template.h > %s" % ( type , header_file))
    
    if needs_update( src_file , "vector_template.c"):
        os.system("sed -e \'s/<TYPE>/%s/g\' vector_template.c > %s" % ( type , src_file ))

    header_list.append( header_file )
    src_list.append( src_file )


define_fmt = "\'%s=\"%s\"\'"
LIB = env.StaticLibrary("util" , src_list , CPPDEFINES = [define_fmt % ("SVN_VERSION"        ,  conf.SVN_VERSION)])


env.InstallLibrary("../lib"    , LIB)
env.InstallHeader("../include" , header_list)
install = env.Alias('install',["../lib" , "../include"])


##################################################################

if SDP_ROOT:
    env.InstallLibrary(conf.SDP_LIB , LIB )
    env.InstallHeader("%s/%s" % (conf.SDP_INCLUDE , "libutil") , header_list)
    SDP_INSTALL = env.Alias('SDP_INSTALL' , [conf.SDP_LIB , conf.SDP_INCLUDE])
 
##################################################################


Default( install )
