name: Code Style

on: [pull_request, workflow_dispatch]

permissions:
   contents: read

jobs:
  formatting:
    name: CMake

    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Setup Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: '3.14'

    - name: Install dependencies
      run: |
        pip install --group format --group types

    - name: Check types
      run: mypy python

    - name: Clang Format
      run: ./script/clang-format --check

    - name: CMake Format
      run: |
        find . -name 'CMakeLists.txt' -o -name '*.cmake' > cmake-src
        xargs cmake-format --check < cmake-src

    - name: Black
      run: |
        black --check .
